language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: phpunit --coverage-text
