language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: phpunit
