language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --coverage-text
